name: EffectSee
main: XanderID\EffectSee\EffectSee
description: See Player effects on UI
api: 5.0.2
version: 1.0.1
author: XanderID

permissions:
 effectsee.use:
  default: op
  description: Allow to see Player Effect
